import 'package:flutter/material.dart';

import '../l10n/locale_context.dart';
import '../models/chat_message.dart';
import '../services/analysis_service.dart';
import '../services/api_client.dart';
import '../theme/app_theme.dart';

/// "Ask about this result" Q&A section, embedded at the bottom of a scan
/// result / analysis detail screen (via [ScanResultView.trailing]).
///
/// Loads any existing chat history for the analysis, lets the user ask
/// follow-up questions, and appends the AI's answer. Every answer is
/// general, non-diagnostic information generated by the backend
/// (`analyses/services/gemini_service.py::generate_chat_answer`) - this
/// widget is just the UI/transport layer, it does not add its own rules.
class AnalysisChatSection extends StatefulWidget {
  final int analysisId;

  const AnalysisChatSection({super.key, required this.analysisId});

  @override
  State<AnalysisChatSection> createState() => _AnalysisChatSectionState();
}

class _AnalysisChatSectionState extends State<AnalysisChatSection> {
  final _service = AnalysisService();
  final _controller = TextEditingController();

  List<ChatMessage> _messages = [];
  bool _loadingHistory = true;
  bool _sending = false;
  String? _error;

  @override
  void initState() {
    super.initState();
    _loadHistory();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _loadHistory() async {
    try {
      final messages = await _service.getChatHistory(widget.analysisId);
      if (!mounted) return;
      setState(() {
        _messages = messages;
        _loadingHistory = false;
      });
    } catch (_) {
      // Best-effort - a fresh analysis with no history yet is not an error.
      if (!mounted) return;
      setState(() => _loadingHistory = false);
    }
  }

  Future<void> _send() async {
    final question = _controller.text.trim();
    if (question.isEmpty || _sending) return;

    setState(() {
      _sending = true;
      _error = null;
    });
    _controller.clear();

    try {
      final exchange = await _service.askQuestion(widget.analysisId, question);
      if (!mounted) return;
      setState(() {
        _messages = [
          ..._messages,
          exchange.userMessage,
          exchange.assistantMessage,
        ];
        _sending = false;
      });
    } on ApiException catch (e) {
      if (!mounted) return;
      setState(() {
        _sending = false;
        _error = e.message;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _sending = false;
        _error = context.tr('common.somethingWrong');
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final c = context.colors;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          context.tr('chat.title'),
          style: TextStyle(
            color: c.textMuted,
            fontWeight: FontWeight.w800,
            fontSize: 12,
            letterSpacing: 0.6,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          context.tr('chat.subtitle'),
          style: TextStyle(color: c.textLight, fontSize: 12, height: 1.4),
        ),
        const SizedBox(height: 14),
        if (_loadingHistory)
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 12),
            child: Center(
              child: SizedBox(
                width: 18,
                height: 18,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  color: c.primary,
                ),
              ),
            ),
          )
        else if (_messages.isNotEmpty)
          Column(
            children: _messages.map((m) => _bubble(c, m)).toList(),
          ),
        if (_sending)
          Padding(
            padding: const EdgeInsets.only(bottom: 10),
            child: Row(
              children: [
                SizedBox(
                  width: 14,
                  height: 14,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    color: c.primary,
                  ),
                ),
                const SizedBox(width: 8),
                Text(
                  context.tr('chat.thinking'),
                  style: TextStyle(color: c.textMuted, fontSize: 12.5),
                ),
              ],
            ),
          ),
        if (_error != null)
          Padding(
            padding: const EdgeInsets.only(bottom: 10),
            child: Text(
              _error!,
              style: TextStyle(color: c.high, fontSize: 12.5),
            ),
          ),
        Row(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Expanded(
              child: TextField(
                controller: _controller,
                minLines: 1,
                maxLines: 4,
                enabled: !_sending,
                decoration: InputDecoration(
                  hintText: context.tr('chat.placeholder'),
                ),
                onSubmitted: (_) => _send(),
              ),
            ),
            const SizedBox(width: 8),
            IconButton.filled(
              onPressed: _sending ? null : _send,
              icon: const Icon(Icons.arrow_upward_rounded),
              style: IconButton.styleFrom(
                backgroundColor: c.primary,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.all(14),
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _bubble(AppColors c, ChatMessage message) {
    final isUser = message.role == ChatRole.user;

    return Align(
      alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        constraints: BoxConstraints(
          maxWidth: MediaQuery.of(context).size.width * 0.78,
        ),
        margin: const EdgeInsets.only(bottom: 10),
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
        decoration: BoxDecoration(
          color: isUser ? c.primary : c.surface2,
          borderRadius: BorderRadius.circular(16),
        ),
        child: Text(
          message.content,
          style: TextStyle(
            color: isUser ? Colors.white : c.text,
            fontSize: 13.5,
            height: 1.4,
          ),
        ),
      ),
    );
  }
}
