apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: skinscan
data:
  DEBUG: "True"
  DB_ENGINE: "postgres"
  DB_NAME: "skinscan"
  DB_USER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
