# Generated by Django 5.2.7 on 2026-07-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('SELF_CARE', 'Self-care'), ('MEDICAL_CONSULT', 'Medical consultation'), ('LIFESTYLE', 'Lifestyle')], max_length=20)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='SkinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='conditions/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('BENIGN', 'Benign'), ('PRECANCEROUS', 'Precancerous'), ('MALIGNANT', 'Malignant'), ('INFLAMMATORY', 'Inflammatory'), ('OTHER', 'Other')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'skin_conditions',
            },
        ),
        migrations.CreateModel(
            name='ConditionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_recommendations', to='core.recommendation')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_recommendations', to='core.skincondition')),
            ],
            options={
                'db_table': 'condition_recommendations',
                'constraints': [models.UniqueConstraint(fields=('condition', 'recommendation'), name='unique_condition_recommendation')],
            },
        ),
    ]
