# Generated by Django 5.2.7 on 2026-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition',
            name='treatment_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
